Yusuke/play画面の作成
SNKK62/TypingGame pull request #14
Opened 2023-11-20 15:16 UTC by takagiyuusuke

仮のやつ

2023-11-21 12:32 UTC, takagiyuusuke commented
Rotate処理の完成

2023-11-21 12:44 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +    setMoveDown(!moveDown);
もしかすると，`setMoveDown(prev => !prev)` みたいな形の方がいいかも

2023-11-21 12:48 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +        // setValues({ ...values, allpattern: newAllPattern as string[] });
このコメントはいらない？

2023-11-21 12:49 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +  // const [gradation, setGradation] = useState<number>(1);
このコメントはいらない？

2023-11-21 12:49 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +        // setValues({ ...values, allpattern: newAllPattern as string[] });
このコメントはいらない？

2023-11-21 12:51 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +      console.log((event as React.KeyboardEvent).key);
デバッグ用？

2023-11-21 12:55 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +      if (judgeType === 1) {
judgeTypeの各条件分岐の下にコメントして欲しい
あと，1,2,3,4だと分かりづらい（マジックナンバー）のでjudegement.tsで定数を定義してインポートしてほしい

2023-11-21 12:56 UTC, SNKK62 commented on frontend/src/app/play/container.tsx
> +'use client';
とりあえずこれは消して大丈夫

2023-11-21 12:59 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +  const [words, setWords] = useState<string[]>([
これってstateな意味ある？定数であるいい気がするsetWordsも使ってないから,
kanasも同様

2023-11-21 13:01 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +          .concat([newEntered as string])
こういうやつも型変換しなくてもいいように型工夫できないかな？

2023-11-21 13:03 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +  const [countS, setCountS] = useState<number>(0);
stateが多いから各stateで，<br>
`const [countS, setCountS] = useState<number>(0); // ....`<br>
みたいな感じでコメントしてほしい（多分少し経ったら自分でもわからなくなると思う笑）

2023-11-21 13:04 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +    setMoveDown(!moveDown);
というかonButtonPushedは消しちゃおう（ボタンも）
あくまでテスト用だと思うので

2023-11-21 13:08 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +          temp = temp + 0.04;
これもなぜ0.04?ってなるから，定数で作ってほしい

2023-11-21 13:09 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +      let temp = -0.04;
結構使ってるからtempじゃなくてもっと名前で伝わった方がいいかも

2023-11-21 13:09 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +      }, 10);
この10も定数でどっかに定義したい

2023-11-21 13:10 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +      <Button onClick={onButtonPushed}>Rotate!</Button>
このボタンは一旦消そう

2023-11-21 13:11 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +    <div style={{ height: screenHeight, width: screenWidth }}>
これも実際には使わないかな，幅と高さは使う側で指定しそう？

2023-11-21 13:16 UTC, SNKK62 commented on frontend/src/components/wordCard.tsx
> +        position: 'absolute',
ここはrelativeの方がいい気もするけどどうだろう？（自信はない）
[https://zero-plus.io/media/css-position-relative/](https://zero-plus.io/media/css-position-relative/)

2023-11-21 13:18 UTC, SNKK62 commented on frontend/src/utils/judgement.ts
> +  //   candidate.push(entry.keys[j]);
このコメントは不要？

2023-11-21 13:18 UTC, SNKK62 commented on frontend/src/utils/judgement.ts
> +  //   for (let k = 0; k < candidate.length; k++) {
このコメントも不要？

2023-11-21 13:22 UTC, SNKK62 commented on frontend/src/utils/judgement.ts
> +const make_goal = (array: string[]): string[] => {
ここれへんの関数も全部キャメルケースにしたいかな
[https://jp-seemore.com/web/4136/](https://jp-seemore.com/web/4136/)

2023-11-21 13:25 UTC, SNKK62 commented on frontend/src/utils/judgement.ts
> +        return [1, newEntereed, newAllPattern, newcount];
他のコメントでも触れたけどここらへんの数字がマジックナンバーになってるから
```
export JUDGE_TYPE = {
  ...: 1,
  ...: 2,
.....
}
```
みたいな感じにしてほしい

2023-11-21 13:27 UTC, SNKK62 commented on frontend/src/utils/judgement.ts
> +  if (isPrefixOf(newEntereed, allPattern)) {
ここら辺の条件分岐も全部条件の下にコメントの行入れよう

2023-11-21 13:27 UTC, SNKK62 requested changes
たくさんコメントしちゃったけど，確認お願い！

2023-11-22 01:25 UTC, takagiyuusuke commented on frontend/src/components/wordCard.tsx
> +        position: 'absolute',
relativeだと本来の描画位置からの相対座標になっちゃって思い通りの動きにならなかったから、とりあえずabsoluteのままにしておきたい

2023-11-22 01:48 UTC, takagiyuusuke commented on frontend/src/components/play/playingCards.tsx
> +          .concat([newEntered as string])
judgement.tsのjudge関数の返値の型を制限することによって実現。

2023-11-22 01:52 UTC, takagiyuusuke commented
wordCardのposition以外は全て修正済。

2023-11-23 14:46 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +  const words: string[] = [
これとkanasはコンポーネント関数の外で定義しよう
(ここに定義するとレンダリングごとに再生成されるはず)

2023-11-23 14:51 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +  const [countS, setCountS] = useState<number>(0); //現在の音節番号
それだったらsoundIndexとかのほうがよくない？
countWもwordIndexの方が分かりやすそうだけどどうかな？

2023-11-23 14:54 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +        //音節の入直が完了した、かつWordが終了した場合
細かいけど入直になってる

2023-11-23 15:09 UTC, SNKK62 commented on frontend/src/utils/judgement.ts
> +  candidate = candidate2;
この操作いる？

2023-11-23 15:10 UTC, SNKK62 commented on frontend/src/utils/judgement.ts
> +  candidate = candidate2;
この操作も要らなそう？

2023-11-23 15:16 UTC, SNKK62 commented on frontend/src/utils/judgement.ts
> +  const newEntereed: string = entered + e;
細かいけど newEnteredでは？

2023-11-23 15:16 UTC, SNKK62 commented on frontend/src/components/wordCard.tsx
> +        position: 'absolute',
OK

2023-11-23 15:27 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +        ...values,
`前の値使うなら，
```
setValues(prev => ({
     ...prev,
     japanesearray: tempJapaneseArray,
     keyarra: tempKeyArray,
}))
```
みたいな形にした方がいい

2023-11-23 15:27 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +        ...values,
と思う

2023-11-23 15:29 UTC, SNKK62 commented on frontend/src/components/play/playingCards.tsx
> +    const handleKeyDown = (event: unknown) => {
これの上の行で
```
TODO：eventの型要修正
```
って書いといて（今は治さなくていい）

2023-11-23 15:37 UTC, SNKK62 requested changes
あとは残ってるコメントの細かいところの対応すればOK

2023-11-24 04:56 UTC, takagiyuusuke commented
Thank you for reviewing!

2023-11-24 06:13 UTC, SNKK62 approved these changes, later dismissed
LGTM! Thanks!

2023-11-25 09:36 UTC, SNKK62 approved these changes
おそらく修正完了

2023-11-25 11:05 UTC, takagiyuusuke reviewed
修正ありがとうございます！

2023-11-25 11:16 UTC, merged