Yusuke/トップ画面の制作
SNKK62/TypingGame pull request #24
Opened 2024-05-10 06:13 UTC by takagiyuusuke

トップ画面を作成完了
SUPABASEとの連携を実装

2024-05-10 06:26 UTC, SNKK62 commented on src/app/choice/actions.ts
> +  if (mode === 0) {
modeが何かの説明とTODOのコメントがないと分からなくなりそう

2024-05-10 06:27 UTC, SNKK62 commented on src/app/choice/container.tsx
> +  function truncateString(str: string): string {
この関数はコンポーネントの外で定義した方がパフォーマンス的に良さそう

2024-05-10 06:28 UTC, SNKK62 commented on src/app/edit/page.tsx
> +  return <A data={data} />;
名前を要修正

2024-05-10 06:35 UTC, SNKK62 commented on src/app/make/page.tsx
> +  const [isEditing, setIsEditing] = useState<number>(-1);
この変数はどういう意味？
isEditingだとbool型を連想させるけど，-1と1?を使ってるのには理由がある？

2024-05-10 06:36 UTC, SNKK62 commented on src/app/play/[id]/page.tsx
> +  return <PlayContainer id={Number(numericId)} />;
parseIntとNumberどっちか？

2024-05-10 06:37 UTC, SNKK62 commented on src/components/header.tsx
> +// import { Menu } from './utils/menu';
不要なコメントアウトは消そう

2024-05-10 06:37 UTC, SNKK62 commented on src/components/header.tsx
> +        <div style={{ display: 'flex', lineHeight: '100%', textAlign: 'center' }}>
ここも不要？

2024-05-10 06:37 UTC, SNKK62 commented on src/components/make/editModal.tsx
> +  onClickCreate,
handleCreateとかの方が分かりやすいかも？

2024-05-10 06:39 UTC, SNKK62 commented on src/components/play/bavkground.tsx
> +export const Background = () => {
背景はもし全部のところで共有ならlayoutとかで設定すれば良さそう

2024-05-10 06:39 UTC, SNKK62 commented on src/components/play/bavkground.tsx
> +export const Background = () => {
それともそもそも使ってない？

2024-05-10 06:40 UTC, SNKK62 commented on src/components/play/playing.tsx
> +  if (combo >= 191) return 200;
マジックナンバーになってるから変数に一回入れて意味を持たせた方が良さそう

2024-05-10 06:40 UTC, SNKK62 commented on src/components/play/playing.tsx
> +      if (values.wordIndex >= words.length - 4) return;
ここもoffsetとかの変数に入れた方がいいかも？

2024-05-10 06:41 UTC, SNKK62 commented on src/components/utils/menu.tsx
> +//         <MenuItem>Top</MenuItem>
このコンポーネント使ってないなら一回消した方がいいかも

2024-05-10 06:41 UTC, SNKK62 commented on src/components/utils/numberDisplay.tsx
> +              color: 'brack',
このコンポーネントのcolorが全部brackになってる

2024-05-10 06:44 UTC, SNKK62 commented on src/utils/judgement.ts
> +  if (!st) return pattern;
stって変数だと分からないから，コメント入れるか名前変えた方がいいかも

2024-05-10 06:45 UTC, SNKK62 requested changes
コメント箇所の確認お願い

2024-05-10 06:46 UTC, SNKK62 commented on src/app/choice/actions.ts
> +  if (mode === 0) {
TODOで書いといて，今は使っている部分だけ実装してあとは消す方がいいかも
基本的に動いているコードだけを残した方がいい

2024-05-10 07:22 UTC, takagiyuusuke commented on src/app/choice/actions.ts
> +  if (mode === 0) {
修正済み

2024-05-10 07:24 UTC, takagiyuusuke commented on src/app/edit/page.tsx
> +  return <A data={data} />;
まだedit機能は実装できてなかった仮のページだったからいったんapp/editごと消した

2024-05-10 07:29 UTC, takagiyuusuke commented on src/app/make/page.tsx
> +  const [isEditing, setIsEditing] = useState<number>(-1);
編集中のワードのインデックス番号を表してる。
0以上ならそのindexのワードを編集するモーダルがopen
-1のときがidle状態
-2のときはタイトルを編集するモーダルがopenする

でも名前がおかしかったから[editingNumber,setEditingNumber]に変更した

2024-05-10 07:37 UTC, takagiyuusuke commented on src/components/play/bavkground.tsx
> +export const Background = () => {
つかってなかった！削除しとく

2024-05-10 07:46 UTC, takagiyuusuke commented on src/components/utils/menu.tsx
> +//         <MenuItem>Top</MenuItem>
OK!!

2024-05-10 07:48 UTC, takagiyuusuke commented on src/components/utils/numberDisplay.tsx
> +              color: 'brack',
(´;ω;｀)

2024-05-10 07:53 UTC, takagiyuusuke commented on src/utils/judgement.ts
> +  if (!st) return pattern;
syllableに変数名を変更

2024-05-10 07:53 UTC, takagiyuusuke commented
THANK YOU FOR REVIEWING!!

2024-05-10 16:03 UTC, SNKK62 commented on src/app/make/page.tsx
> +  const isNotEmpty = () => {
isNotEmptyっていう命名は混乱しやすいから，isEmptyに直して判定の時に否定とった方が分かりやすいかも

2024-05-10 16:07 UTC, SNKK62 commented on src/app/make/page.tsx
> +  const isNotEmpty = () => {
あと，これもコンポーネントの外に出してもいいかも
多分そうすると関数の実装も綺麗で
```js
const isEmpty = (data) => {
    return !data.some(item => item.isActive)
}
```
みたいな感じで書けないかな？詳しい挙動は調べて欲しいけど

2024-05-10 16:22 UTC, SNKK62 commented on src/app/make/actions.ts
> +  const insertArray: { id: number; word: string; kana: string; isActive: boolean }[] = [];
```js
const insertArray = wordDataArray.filter(item => item.isActive)
```
と同じ意味？
それだったら１行にまとめたほうが読みやすいかも

2024-05-10 16:51 UTC, SNKK62 commented on src/app/make/page.tsx
> +  const [isEditing, setIsEditing] = useState<number>(-1);
なるほど，ちょっと読み手がわかりにくいから．
```js
const [editingId, setEditingId] = useState<number | undefined>();
const [isEditingTitle, setIsEditingTitle] = useState(false);
const [isIdle, setIsIdle] = useState(true);
```
とかの責務別に分けた方がいいと思う

2024-05-10 16:54 UTC, SNKK62 requested changes
dataのtypeを`{word: string, kana: string, isActive: boolean}`みたいな感じで定義してると思うけど，これをどこか`model`ディレクトリを作ってそこにファイルを作って
```ts
type  ... = {word: string, kana: string, isActive: boolean}
```
みたいなのを定義してそれを外部ファイルで使った方がいいと思う（重複コードを避けるため）

2024-05-13 13:18 UTC, takagiyuusuke commented on src/components/play/playing.tsx
> +  if (combo >= 191) return 200;
多分直せたはず

2024-05-13 13:19 UTC, takagiyuusuke commented on src/app/make/page.tsx
> +  const [isEditing, setIsEditing] = useState<number>(-1);
OK!仕様変更した！

2024-05-13 13:21 UTC, takagiyuusuke commented
next.jsのバージョンをアップデートしたらゲームのアルゴリズムがバグったから多少playing.tsxの関数を変更して修正した。
lintとrun buildは通過することを確認済み

2024-05-13 14:00 UTC, SNKK62 approved these changes
LGTM! Thanks!

2024-05-13 14:00 UTC, merged